import { calculateMealQuality, calculateSatietyScore } from "@/lib/calculations";
import type { FoodItem } from "@/types/food";
import type { Insight } from "@/types/insight";
import type { MealLog, SavedMeal } from "@/types/meal";
import type { DailyLog, UserProfile, WeightLog } from "@/types/user";

export const demoUser: UserProfile = {
  id: "demo-user",
  name: "Ava Sharma",
  email: "ava@example.com",
  image: "",
  age: 28,
  gender: "Female",
  height: 165,
  weight: 68,
  goal: "lose",
  activityLevel: "moderate",
  dailyCalories: 1950,
  macroTargets: { protein: 125, carbs: 205, fat: 60, fiber: 30 },
  flexibleBudget: { mode: "weekend", weekdayCalories: 1900, weekendCalories: 2200 },
  waterTarget: 2600,
};

export const foodLibrary: FoodItem[] = [
  {
    id: "food-1",
    name: "Greek Yogurt Bowl",
    brand: "Homemade",
    servingSize: 250,
    unit: "g",
    calories: 220,
    protein: 20,
    carbs: 24,
    fat: 4,
    fiber: 5,
    sugar: 12,
    source: "favorite",
    category: "breakfast",
    verified: true,
  },
  {
    id: "food-2",
    name: "Chicken Burrito Bowl",
    brand: "Meal Prep",
    servingSize: 380,
    unit: "g",
    calories: 540,
    protein: 38,
    carbs: 55,
    fat: 18,
    fiber: 11,
    sugar: 6,
    source: "custom",
    category: "lunch",
  },
  {
    id: "food-3",
    name: "Iced Vanilla Latte",
    brand: "Cafe",
    servingSize: 350,
    unit: "ml",
    calories: 210,
    protein: 7,
    carbs: 29,
    fat: 7,
    fiber: 0,
    sugar: 24,
    source: "custom",
    category: "drink",
  },
  {
    id: "food-4",
    name: "Lentil Veggie Soup",
    brand: "Homemade",
    servingSize: 320,
    unit: "g",
    calories: 280,
    protein: 18,
    carbs: 34,
    fat: 7,
    fiber: 13,
    sugar: 7,
    source: "favorite",
    category: "dinner",
  },
  {
    id: "food-5",
    name: "Office Canteen Paneer Wrap",
    brand: "Office Canteen",
    servingSize: 1,
    unit: "wrap",
    calories: 430,
    protein: 20,
    carbs: 38,
    fat: 19,
    fiber: 6,
    sugar: 5,
    source: "custom",
    category: "lunch",
  },
];

const mealBase: MealLog[] = [
  {
    id: "meal-1",
    userId: demoUser.id,
    date: "2026-03-22T08:00:00.000Z",
    mealType: "breakfast",
    items: [
      {
        food: foodLibrary[0],
        quantity: 250,
        unit: "g",
        calories: 220,
        protein: 20,
        carbs: 24,
        fat: 4,
        fiber: 5,
      },
    ],
    totalCalories: 220,
    totalProtein: 20,
    totalCarbs: 24,
    totalFat: 4,
    totalFiber: 5,
    protein: 20,
    carbs: 24,
    fat: 4,
    fiber: 5,
    hungerBefore: 7,
    fullnessAfter: 8,
    mood: "energized",
    stressLevel: 3,
    notes: "Easy breakfast before work.",
  },
  {
    id: "meal-2",
    userId: demoUser.id,
    date: "2026-03-22T13:10:00.000Z",
    mealType: "lunch",
    items: [
      {
        food: foodLibrary[1],
        quantity: 380,
        unit: "g",
        calories: 540,
        protein: 38,
        carbs: 55,
        fat: 18,
        fiber: 11,
      },
    ],
    totalCalories: 540,
    totalProtein: 38,
    totalCarbs: 55,
    totalFat: 18,
    totalFiber: 11,
    protein: 38,
    carbs: 55,
    fat: 18,
    fiber: 11,
    hungerBefore: 8,
    fullnessAfter: 9,
    mood: "calm",
    stressLevel: 4,
  },
  {
    id: "meal-3",
    userId: demoUser.id,
    date: "2026-03-22T16:30:00.000Z",
    mealType: "snack",
    items: [
      {
        food: foodLibrary[2],
        quantity: 350,
        unit: "ml",
        calories: 210,
        protein: 7,
        carbs: 29,
        fat: 7,
        fiber: 0,
      },
    ],
    totalCalories: 210,
    totalProtein: 7,
    totalCarbs: 29,
    totalFat: 7,
    totalFiber: 0,
    protein: 7,
    carbs: 29,
    fat: 7,
    fiber: 0,
    hungerBefore: 5,
    fullnessAfter: 4,
    mood: "craving",
    stressLevel: 7,
    notes: "Coffee craving during a long meeting.",
  },
];

export const mealLogs = mealBase.map((meal) => ({
  ...meal,
  qualityScore: calculateMealQuality(meal),
  satietyScore: calculateSatietyScore(meal),
}));

export const savedMeals: SavedMeal[] = [
  {
    id: "saved-1",
    userId: demoUser.id,
    name: "Mom's chicken curry",
    items: [mealLogs[1].items[0]],
    tags: ["family", "high protein"],
    favorite: true,
    createdAt: "2026-03-10T11:00:00.000Z",
  },
  {
    id: "saved-2",
    userId: demoUser.id,
    name: "Office canteen lunch",
    items: [
      {
        food: foodLibrary[4],
        quantity: 1,
        unit: "wrap",
        calories: 430,
        protein: 20,
        carbs: 38,
        fat: 19,
        fiber: 6,
      },
    ],
    tags: ["canteen", "weekday"],
    createdAt: "2026-03-17T11:00:00.000Z",
  },
];

export const dailyLog: DailyLog = {
  id: "daily-1",
  userId: demoUser.id,
  date: "2026-03-22",
  waterIntake: 1850,
  sleepHours: 5.8,
  cravings: ["sweet", "coffee"],
  steps: 7420,
  stressLevel: 7,
  notes: "A meeting-heavy day with late lunch.",
};

export const insights: Insight[] = [
  {
    id: "insight-1",
    userId: demoUser.id,
    date: "2026-03-22",
    type: "sleep",
    title: "Sleep is nudging snack calories up",
    message: "On days below 6 hours of sleep, your snack calories trend 24% higher. Consider a protein-forward afternoon snack on low-sleep days.",
    priority: "high",
  },
  {
    id: "insight-2",
    userId: demoUser.id,
    date: "2026-03-22",
    type: "satiety",
    title: "Lunch is your best fullness-per-calorie meal",
    message: "Your burrito bowl scored strongest for satiety. Meals with protein plus fiber are keeping you steadier than coffee-based snacks.",
    priority: "medium",
  },
  {
    id: "insight-3",
    userId: demoUser.id,
    date: "2026-03-22",
    type: "sugar",
    title: "Hidden calories detected in drinks",
    message: "Sweet coffee add-ons are contributing more calories than your planned snack. Switching to a lower-sugar latte would save about 90 calories.",
    priority: "medium",
  },
];

export const weightLogs: WeightLog[] = [
  { id: "weight-1", userId: demoUser.id, date: "2026-03-01", weight: 69.4 },
  { id: "weight-2", userId: demoUser.id, date: "2026-03-08", weight: 69.1 },
  { id: "weight-3", userId: demoUser.id, date: "2026-03-15", weight: 68.6 },
  { id: "weight-4", userId: demoUser.id, date: "2026-03-22", weight: 68.0 },
];
